version: '3.3'
services:
  mysql:
    image: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - "MYSQL_DATABASE=mission_data"
      - "MYSQL_USER=brunno"
      - "MYSQL_PASSWORD=Database01"
      - "MYSQL_ROOT_PASSWORD=Database01"
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - 3306:3306

  adminer:
    image: 'adminer'
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql: